# Generated by Django 3.0.4 on 2020-04-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypageapp', '0002_auto_20200404_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfInfoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True, max_length=260)),
                ('location', models.CharField(blank=True, max_length=260)),
                ('document', models.FileField(upload_to='profile_pic/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfInfo',
        ),
    ]
